// Generated by scripts/mascot-frames.py - do not edit by hand.
// Frames in clip order, each with its gaze direction on a unit circle (x right, y down);
// `center` is the index of the neutral frame, where the mirrored path joins the original.
export const MASCOT_FRAMES = {
  "dir": "/mascot-frames",
  "width": 420,
  "height": 445,
  "face": {
    "x": 0.503,
    "y": 0.323
  },
  "center": 34,
  "frames": [
    {
      "file": "f00.webp",
      "x": 0.341,
      "y": 0.235
    },
    {
      "file": "f01.webp",
      "x": 0.434,
      "y": 0.157
    },
    {
      "file": "f02.webp",
      "x": 0.526,
      "y": 0.052
    },
    {
      "file": "f03.webp",
      "x": 0.605,
      "y": 0.019
    },
    {
      "file": "f04.webp",
      "x": 0.685,
      "y": 0.004
    },
    {
      "file": "f05.webp",
      "x": 0.742,
      "y": -0.002
    },
    {
      "file": "f06.webp",
      "x": 0.786,
      "y": -0.008
    },
    {
      "file": "f07.webp",
      "x": 0.816,
      "y": -0.017
    },
    {
      "file": "f08.webp",
      "x": 0.777,
      "y": -0.029
    },
    {
      "file": "f09.webp",
      "x": 0.751,
      "y": -0.046
    },
    {
      "file": "f10.webp",
      "x": 0.72,
      "y": -0.057
    },
    {
      "file": "f11.webp",
      "x": 0.699,
      "y": -0.068
    },
    {
      "file": "f12.webp",
      "x": 0.669,
      "y": -0.079
    },
    {
      "file": "f13.webp",
      "x": 0.648,
      "y": -0.093
    },
    {
      "file": "f14.webp",
      "x": 0.621,
      "y": -0.104
    },
    {
      "file": "f15.webp",
      "x": 0.592,
      "y": -0.113
    },
    {
      "file": "f16.webp",
      "x": 0.573,
      "y": -0.128
    },
    {
      "file": "f17.webp",
      "x": 0.56,
      "y": -0.152
    },
    {
      "file": "f18.webp",
      "x": 0.565,
      "y": -0.153
    },
    {
      "file": "f19.webp",
      "x": 0.395,
      "y": -0.146
    },
    {
      "file": "f20.webp",
      "x": 0.374,
      "y": -0.138
    },
    {
      "file": "f21.webp",
      "x": 0.369,
      "y": -0.117
    },
    {
      "file": "f22.webp",
      "x": 0.37,
      "y": -0.105
    },
    {
      "file": "f23.webp",
      "x": 0.382,
      "y": -0.095
    },
    {
      "file": "f24.webp",
      "x": 0.39,
      "y": -0.077
    },
    {
      "file": "f25.webp",
      "x": 0.392,
      "y": -0.058
    },
    {
      "file": "f26.webp",
      "x": 0.403,
      "y": -0.037
    },
    {
      "file": "f27.webp",
      "x": 0.408,
      "y": -0.016
    },
    {
      "file": "f28.webp",
      "x": 0.397,
      "y": 0.009
    },
    {
      "file": "f29.webp",
      "x": 0.385,
      "y": 0.066
    },
    {
      "file": "f30.webp",
      "x": 0.339,
      "y": 0.147
    },
    {
      "file": "f31.webp",
      "x": 0.189,
      "y": 0.146
    },
    {
      "file": "f32.webp",
      "x": 0.118,
      "y": 0.055
    },
    {
      "file": "f33.webp",
      "x": 0.059,
      "y": 0.023
    },
    {
      "file": "f34.webp",
      "x": 0.0,
      "y": 0.0
    },
    {
      "file": "f35.webp",
      "x": -0.019,
      "y": 0.286
    },
    {
      "file": "f36.webp",
      "x": -0.076,
      "y": 0.292
    },
    {
      "file": "f37.webp",
      "x": -0.342,
      "y": 0.269
    },
    {
      "file": "f38.webp",
      "x": -0.373,
      "y": 0.185
    },
    {
      "file": "f39.webp",
      "x": -0.42,
      "y": 0.185
    },
    {
      "file": "f40.webp",
      "x": -0.478,
      "y": 0.198
    },
    {
      "file": "f41.webp",
      "x": -0.529,
      "y": 0.218
    },
    {
      "file": "f42.webp",
      "x": -0.597,
      "y": 0.246
    },
    {
      "file": "f43.webp",
      "x": -0.648,
      "y": 0.276
    },
    {
      "file": "f44.webp",
      "x": -0.697,
      "y": 0.306
    },
    {
      "file": "f45.webp",
      "x": -0.747,
      "y": 0.342
    },
    {
      "file": "f46.webp",
      "x": -0.791,
      "y": 0.382
    },
    {
      "file": "f47.webp",
      "x": -0.82,
      "y": 0.42
    },
    {
      "file": "f48.webp",
      "x": -0.873,
      "y": 0.479
    }
  ]
} as const;
